#!/usr/bin/env bash

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM)
for STAGED_FILE in $STAGED_FILES; do
    # Confirm all staged Go files have been formatted
    if [[ $STAGED_FILE == *.go ]]; then
        if [[ $(git show :$STAGED_FILE | gofmt -s -l) ]]; then
            echo "gofmt error on: $STAGED_FILE"
            exit 1
        fi

        if [[ $(git show :$STAGED_FILE | goimports -l) ]]; then
            echo "goimports error on: $STAGED_FILE"
            exit 1
        fi
    fi
done;

make
